; $FileInfo: foxfile.ini - Last Update: 8/26/2025 Ver. 0.21.4 RC 1 - Author: cooldude2k $

[config]
default = FoxFile
proname = PyFoxFile
includedef = true
useinmem = true
usememfd = false
usespoolfile = false
spoolfilesize = 4194304
filebuffsize = 262144
advancedlist = true
altinode = false
newstyle = true

[FoxFile]
len = 7
hex = 466f7846696c65
ver = 001
name = FoxFile
magic = FoxFile
delimiter = \x00
extension = .fox

[KitsuneFile]
len = 11
hex = 4b697473756e6546696c65
ver = 001
name = KitsuneFile
magic = KitsuneFile
delimiter = \x00
extension = .kitsune

[UwUFile]
len = 7
hex = 55775546696c65
ver = 001
name = UwUFile
magic = UwUFile
delimiter = \x00
extension = .UwU

[\u30ad\u30c4\u30cd\u30d5\u30a1\u30a4\u30eb]
len = 21
hex = e382ade38384e3838de38395e382a1e382a4e383ab
ver = 001
name = KitsuneFairu
magic = \u30ad\u30c4\u30cd\u30d5\u30a1\u30a4\u30eb
delimiter = \x00
extension = .\u30AD\u30C4\u30CD

[\u304d\u3064\u306d\u30d5\u30a1\u30a4\u30eb]
len = 21
hex = e382ade38384e3838de38395e382a1e382a4e383ab
ver = 001
name = KitsuneFairu
magic = \u304d\u3064\u306d\u30d5\u30a1\u30a4\u30eb
delimiter = \x00
extension = .\u304D\u3064\u306D

[\u72d0\u30d5\u30a1\u30a4\u30eb]
len = 15
hex = e382ade38384e3838de38395e382a1e382a4e383ab
ver = 001
name = KitsuneFairu
magic = \u72d0\u30d5\u30a1\u30a4\u30eb
delimiter = \x00
extension = .\u72D0

[\u72d0\u72f8\u6587\u4ef6]
len = 12
hex = e78b90e78bb8e69687e4bbb6
ver = 001
name = HúlíWénjiàn
magic = \u72d0\u72f8\u6587\u4ef6
delimiter = \x00
extension = .\u72D0\u72F8

[\uc5ec\uc6b0\ud30c\uc77c]
len = 12
hex = ec97acec9ab0ed8c8cec9dbc
ver = 001
name = YeouPa-il
magic = \uc5ec\uc6b0\ud30c\uc77c
delimiter = \x00
extension = .\uC5EC\uC6B0

[\u57fa\u6b21\u5185\u6cd5\u4f0a\u9c81]
len = 18
hex = e59fbae6aca1e58685e6b395e4bc8ae9b281
ver = 001
name = JīCìNèiFǎYīLǔ
magic = \u57fa\u6b21\u5185\u6cd5\u4f0a\u9c81
delimiter = \x00
extension = .\u57fa\u6b21\u5185

[\ud0a4\uce20\ub124\ud30c\uc77c]
len = 15
hex = ed82a4ecb8a0eb84a4ed8c8cec9dbc
ver = 001
name = KicheunePa-il
magic = \ud0a4\uce20\ub124\ud30c\uc77c
delimiter = \x00
extension = .\ud0a4\uce20\ub124
